# Generated by Django 4.1.1 on 2022-09-27 13:36

from django.db import migrations, models
import django.db.models.deletion
import pictures.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoCartao', models.CharField(choices=[('C', 'Credito'), ('D', 'Debito')], default='D', max_length=1)),
                ('limiteCartao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numeroCartao', models.IntegerField()),
                ('cvcCartao', models.CharField(max_length=4)),
                ('nomeCartao', models.CharField(max_length=20)),
                ('validadeCartao', models.CharField(max_length=5)),
                ('diaVencFatura', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCliente', models.CharField(max_length=50)),
                ('dataNascimento', models.DateField()),
                ('genero', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Nao informado')], default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(max_length=4)),
                ('numeroConta', models.CharField(max_length=7)),
                ('tipoConta', models.CharField(choices=[('P', 'Poupanca'), ('C', 'Corrente'), ('S', 'Salario')], default='C', max_length=1)),
                ('saldoConta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monay.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusEmprest', models.CharField(choices=[('A', 'Autorizado'), ('N', 'Negado')], default='N', max_length=1)),
                ('dataEmprest', models.DateField()),
                ('valorEmprest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qtdParcelas', models.PositiveSmallIntegerField()),
                ('jurosEmprest', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='FotosCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('foto', pictures.models.PictureField(aspect_ratios=[None], breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, file_types=['WEBP'], grid_columns=12, pixel_densities=[1, 2], upload_to='loja/imagens')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpfUsuario', models.CharField(max_length=14)),
                ('senhaUsuario', models.CharField(max_length=15)),
                ('statusUsuario', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorTransacao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dataTransacao', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatario', to='monay.conta')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remetente', to='monay.conta')),
            ],
        ),
        migrations.CreateModel(
            name='PgtoEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorPgto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dataPgto', models.DateField()),
                ('dataVenc', models.DateField()),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monay.emprestimo')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeContato', models.CharField(max_length=50)),
                ('chaveTipo', models.CharField(choices=[('C', 'CPF/CNPJ'), ('E', 'Email'), ('T', 'Telefone')], default='T', max_length=1)),
                ('chaveValor', models.CharField(max_length=50)),
                ('contaDestinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contaDestinatario', to='monay.conta')),
                ('contaRemetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contaRemetente', to='monay.conta')),
            ],
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataVencimento', models.DateField()),
                ('valorFatura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dataPagamento', models.DateField()),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monay.cartao')),
            ],
        ),
        migrations.CreateModel(
            name='Extrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorExtrato', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipoExtrato', models.CharField(max_length=20)),
                ('dataExtrato', models.DateTimeField(auto_now_add=True)),
                ('contaExtrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monay.conta')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=5)),
                ('rua', models.CharField(max_length=15)),
                ('bairro', models.CharField(max_length=15)),
                ('cidade', models.CharField(max_length=15)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monay.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefoneCliente', models.CharField(max_length=11)),
                ('emailCliente', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monay.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='fotoCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monay.fotoscliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monay.usuario'),
        ),
        migrations.AddField(
            model_name='cartao',
            name='contaCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monay.conta'),
        ),
    ]
