# Generated by Django 4.1.1 on 2022-10-06 12:08

from django.db import migrations
import pictures.models


class Migration(migrations.Migration):

    dependencies = [
        ('monay', '0002_alter_fotoscliente_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fotoCliente',
            field=pictures.models.PictureField(aspect_ratios=[None], breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, file_types=['WEBP'], grid_columns=12, height_field=500, pixel_densities=[1, 2], upload_to='loja/imagens', width_field=500),
        ),
        migrations.DeleteModel(
            name='FotosCliente',
        ),
    ]
